version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "OtaUpdateLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l45570p5zn1z"
s3_prefix = "OtaUpdateLambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"